version: '3.7'
services : 
    symrise-backend:
        container_name: symrise-backend-${NODE_ENV}
        build:
            context: .
        depends_on:
            - symrise-db
        networks:
            - symrise-network
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            HOST: ${HOST}
            DATABASE_TYPE: ${DATABASE_TYPE}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_NAME: ${DATABASE_NAME}
            SECRET_JWT: ${SECRET_JWT}
        ports:
            - "${PORT}:${PORT}"
    symrise-db:
        container_name: symrise-db-${NODE_ENV}
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: "%"
        ports: 
            - "${DATABASE_EXTERNAL_PORT}:${DATABASE_PORT}"
        networks:
            - symrise-network
        volumes:
            - database-volume:/var/lib/mysql

volumes:
    database-volume:
        name: symrise-database-volume-${NODE_ENV}

networks:
    symrise-network:
        name: symrise-backend-network-${NODE_ENV}